# Generated by Django 4.2.4 on 2023-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='category',
            field=models.CharField(choices=[('Baverages', 'Baverages'), ('South Indians', 'South Indians')], default='Baverages', max_length=15),
        ),
    ]
