# Generated by Django 4.2.4 on 2023-10-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_table_cart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.table'),
        ),
    ]
