# Generated by Django 4.2.4 on 2023-10-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='User',
            new_name='user',
        ),
    ]
